0no-co/gql.tada

src/__tests__/document.test-d.ts, src/__tests__/introspection.test-d.ts, src/typed-document/index.ts, src/typed-document/variables.ts
Seems currently bugged, getting to the bottom of it
```
const actual: {
test: "BigTodo" | "SmallTodo" | null;
}
```
=> testing interfaces

.changeset/mean-geckos-dream.md, src/__tests__/selection.test-d.ts, src/selection.ts
When a `__typename` field is used on an abstract type’s selection set its value type wouldn’t be exact and instead a union of all possible types unless all possible types have selections containing a `__typename` field themselves.
```graphql
{
test { # possible types: A / B
__typename
... on B {
field
}
}
}
```
The above would result in an incorrect inference since `B`’s selection set doesn't contain `__typename` itself:
```ts
const before: {
test: {
__typename: 'A' | 'B';
} | {
__typename: 'A' | 'B';
field: unknown;
};
};
const after: {
test: {
__typename: 'A';
} | {
__typename: 'B';
field: unknown;
};
};
```
- Move `__typename` field handling to the selection handler that handles all possible types separately
- Remove field handling entirely in favour of always handling fields per …
=> fix: Fix __typename fields on abstract selections not being exact

src/__tests__/selection.test-d.ts
This doesn't actually fix anything, but covers more test cases that may turn out to be tricky in the future.
- Add tests containing optional fragment spreads
=> test: Expand tests for more optional fragment spreads

.changeset/neat-numbers-shake.md, src/__tests__/api.test-d.ts, src/api.ts
When a complex fragment type (e.g. any fragment that derives to a union type of multiple object shapes) is passed to `readFragment()` then the return type would only infer as the first type of the union.
```ts
// derives to `{ wallOfText: string } | { maxLength: number }`
const fragment = graphql(`
fragment Fields on ITodo {
... on BigTodo {
wallOfText
}
... on SmallTodo {
maxLength
}
}
`);
// previously derived to: `{ wallOfText: string }`
// rather than: `{ wallOfText: string } | { maxLength: number }`
const fields = readFragment(fragment, data);
```
- Add tests for `readFragment` inputs
- Remove `Data` generic on `readFragment` and instead infer `Data` from `Document` directly
=> fix: Fix readFragment() not deriving complex return types

.changeset/shaggy-lies-allow.md, website/astro.config.mjs
Adds a wand emoji in the header.
=> Add wand emoji in header

.changeset/dry-actors-exercise.md, src/introspection.ts, src/selection.ts
Resolves #22
Prevent type inference for schemas with “huge” root types (i.e. types with an excessive amount of fields) from failing introspection mapping.
This is done by omitting `args` from the introspection mapping to slim down the type, and by preventing a match against every field from accidentally happening by removing `IntrospectionField` matching from `ObjectLikeType`.
- Fix `ObjectLikeType` to not include `IntrospectionField` matching
- Remove `args` from fields in `mapObject` and `mapInterface`
=> fix: Prevent introspection mapping on schemas with huge root types from failing

.changeset/tiny-cameras-battle.md, src/__tests__/fixtures/simpleSchema.ts, src/introspection.ts
Resolves #22
This removes any unnecessary and redundant constraints in `IntrospectionQuery`, which previously forced TypeScript to recursively check the input `IntrospectionQuery` data (i.e. the schema data a user gives us) against the constraint type.
This meant that TypeScript was spending a lot of time in `recursiveTypeRelatedTo`, only to recursively unroll an introspection schema that we were mapping and checking anyway.
Instead, this constraint is now removed and also doesn't affect code paths that run after `mapIntrospection` has run already.
- Remove `args` from `IntrospectionField`
- Remove `interfaces` from `IntrospectionObjectType` and `IntrospectionInterfaceType`
- Change `types` constraint to `readonly any[]` in `IntrospectionSchema`
=> fix: Remove redundant constraints on IntrospectionQuery causing TS perf bottlenecks

website/src/content/docs/get-started/installation.mdx, website/src/content/docs/reference/gql-tada-api.mdx, website/src/content/docs/reference/graphqlsp-config.mdx
Depends on https://github.com/0no-co/GraphQLSP/pull/184
This updates the docs to prefer only ever outputting a `d.ts` file in GraphQLSP.
In the linked PR, the `introspection` type will be exported in `.d.ts` file, making it possible to call `initGraphQLTada` with it, without switching the GraphQLSP output to `.ts` files.
=> docs: Prefer instructions that only create .d.ts file

.changeset/fair-pillows-repair.md, src/__tests__/selection.test-d.ts, src/selection.ts
Resolves #30
This supports client-controlled nullability directives, as implemented for instance in [in Graphcache for an example.](https://formidable.com/open-source/urql/docs/graphcache/local-directives/#client-controlled-nullability)
When applied,
- `@_optional` / `@optional` turns a non-nullable field into a nullable one.
- `@_required` / `@required` turns a nullable field into a non-nullable one.
- Add `getTypeDirective` as `unwrapType` input and override type as required
=> feat: Implement support for `@_optional` and `@_required` on fields

.changeset/sweet-birds-grab.md, src/parser.ts
This improves the parser’s performance by eliminating unused generic constraints.
- Remove unused `In extends string` constraints
- Remove unused `Const extends boolean` constraints
- Turn `unknown[]` constraints to `any[]`
=> fix: Improve parser performance

.changeset/four-bats-impress.md, src/__tests__/selection.bench.ts, src/selection.ts, src/variables.ts
This improves the selection and variables’s type inference/derivation performance by eliminating unused generic constraints, unused infers, and unnecessary nested type checks.
- Remove unused generics
- Remove unused `infer`s from variables types
- Unwrap `isOptionalRec` (renamed to `isOptional`) and `getTypeDirective`
=> fix: Improve selection and variables performance

.changeset/grumpy-dancers-jam.md, src/__tests__/api.test-d.ts, src/api.ts, src/namespace.ts
Currently we allow any documents where fragment definition documents are expected specifically,
- `FragmentOf<typeof fragment>` must only accept fragments
- `readFragment(fragment, data)` must only accept fragments
Instead, `[$tada.definition]?: never` was basically allowing any documents, which is why it's being replaced in this PR with `[$tada.definition]?: void` for operation documents
- Replace `DocumentDefDecorationLike` to clean up duplicate type
- Default decorations to `void` rather than `never`
=> feat: Tighten types to not accept operations where fragments are expected

.changeset/dry-seals-laugh.md, .changeset/witty-moose-kiss.md, src/__tests__/api.test-d.ts, src/api.ts, src/index.ts, src/namespace.ts, website/src/content/docs/reference/gql-tada-api.mdx
Resolve #38
This PR, when applied, adds two new utilities, as documented in the website changes.
- `maskFragments` accepts a list of fragments and the combined data (or a list of such) matching the fragments’ result type, and returns the combined fragment masks of the fragments.
- `unsafe_readResult` accepts a document and its result type (without fragment refs) and **unsafely** casts it to the result type (as an alternative to `as any as ResultType<typeof document>`
The former operation is safe but cumbersome when creating test data.
The latter is unsafe, but safer than an `as any` cast.
- Add `maskFragments`
- Add `unsafe_readResult`
=> feat: Add `unsafe_readResult()` and `maskFragments()` utilities

.changeset/mighty-jokes-repair.md, src/__tests__/api.test-d.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/introspection.test-d.ts, src/api.ts, src/introspection.ts, website/src/content/docs/reference/gql-tada-api.mdx
Resolves #44
This adds a new identity method on `graphql.scalar()` that can either be used to retrieve or type check the type of scalars and enums.
To retrieve the type of a scalar it's used with `typeof`:
```ts
type testEnum = ReturnType<typeof graphql.scalar<'test'>>;
```
To check the type of a scalar it's used by calling it:
```ts
const test = graphql.scalar('test', 'more');
```
- Add `graphql.scalar()` utility
- Update docs
=> feat: Add `graphql.scalar()` utility to check/retrieve scalar/enum types

.changeset/short-teachers-begin.md, src/selection.ts, src/variables.ts
See #46
This is partially extracted from #46 and one other opportunity where tail recursion was missing. The changes have been carried over one-by-one and split up.
One change is missing (`UnionAcc`) since it doesn't trigger a tail recursion case in TypeScript, since it wasn't on a single type, i.e. non-mutually recursive type alias, but on several types, and hoisted too far. So, that change hasn't been carried over. The benchmarks also seem to confirm that that change isn't relevant for this PR.
(Note: In general, the benchmarks, when `selection` is run in isolation, give a good indicator of whether tail recursion is helping)
In some of these cases, tail recursion hasn't increased performance, but the opportunity to add them is good nonetheless.
- Make `_getPossibleTypeSelectionRec` tail …
=> fix: Add tail recursion where it's possible but missing

.changeset/cuddly-kiwis-cheer.md, src/__tests__/api.test-d.ts, src/__tests__/introspection.test-d.ts, src/api.ts, src/introspection.ts
Resolves #47
Retrieving a large `union` of type names and then potentially exposing the `tsserver` to it seems to cause a crash. Furthermore, evaluating the schema to retrieve all types, filter them by their kind, and then extracting the names seems to also cause issues.
I noticed that auto-complete in place of a generic isn't possible anyway, so we can save ourselves the effort. We can potentially readd it to the `graphql.scalar` argument itself, but it doesn't really seem worth it.
- Remove `getScalarTypeNames`
- Remove type names constraint from `graphql.scalar`
=> fix: Remove generic constraint on `graphql.scalar`’s type name to improve performance

.changeset/rude-houses-rest.md, src/__tests__/api.test-d.ts, src/api.ts, src/namespace.ts, website/src/content/docs/guides/fragment-colocation.mdx, website/src/content/docs/reference/gql-tada-api.mdx
**This is a feature preview, and while we consider it stable and ready for production, we may consider changing it before the next `minor` release!**
This feature is enabled by configuring `gql.tada` with the `disableMasking: true` flag.
```ts
export const graphql = initGraphQLTada<{
introspection: introspection;
disableMasking: true;
}>();
```
When enabled, fragment masking is completely disabled, similar to if you added `@_unmask` to every single fragment.
We consider this a necessary addition for some projects that would otherwise run into trouble when having a “document cache” where query data is modified as a whole, which is a bad match for fragment masking.
- Add `disableMasking: flag` forcing `masked: false` on fragment references
=> feat: Support `disableMasking: true` option to disable fragment masking globally 

.changeset/strong-ducks-shop.md, src/__tests__/fixtures/simpleIntrospection.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/variables.test-d.ts, src/variables.ts
Resolve #71
The case of `defaultValue` not being `null | undefined` wasn't being handled when deriving types for input object fields in variables.
This PR adds the missing match.
- Add match for `defaultValue` to input objects’ fields
=> fix: Add missing case for input object fields with default value

.changeset/rich-boxes-smash.md, packages/cli-utils/src/tada.ts
`npx gql.tada generate` is resolving the schema.graphql file path from *parent* of CWD instead of the CWD.
e.g.
```json
// tsconfig.json
{
"plugins": [
{
"name": "@0no-co/graphqlsp",
"schema": "./graphql/schema.graphql",
"tadaOutputLocation": "./types/graphql-env.d.ts"
}
]
}
```
Assume CWD is `/path/to/my_projects/my_app`
Run `npx gql.tada generate` gets error:
```
Something went wrong while writing the introspection file [Error: ENOENT: no such file or directory, open '/path/to/my_projects/graphql/schema.graphql']
```
- remove `path.dirname()`
NOTE: I would add a test-case but I don't see tests for CLI yet
=> fix cli schema path resolver

.changeset/breezy-queens-bow.md, src/__tests__/introspection.test-d.ts, src/__tests__/variables.test-d.ts, src/api.ts, src/introspection.ts, src/variables.ts
`graphql.scalar()` currently allows scalars and enums to be resolved from the given introspection schema, however, it differed from `getScalarType` in `variables.ts` in that it didn't resolve input objects.
- Reuse logic in `variables.ts` for `graphql.scalar`
=> fix: Allow `graphql.scalar` to resolve types for input objects

.changeset/nervous-socks-relate.md, src/index.ts, src/namespace.ts
This is required for projects that are configured with `isolatedModules: true`.
When this is set, the `$tada` symbols can't be referenced and hence an error is emitted by `tsserver`/`tsc`.
Exporting `$tada` fixes this.
- Re-export `$tada`
- Mark `$tada` as `@internal` in ts docs
=> fix: Export `$tada` to fix `isolatedModules` projects

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/site.yml
Currently we see a lot of warnings in the CI about updating our actions. https://github.com/0no-co/gql.tada/actions/runs/8067503114
=> chore: update actions to node 20

.changeset/orange-badgers-decide.md, src/__tests__/api.test-d.ts, src/__tests__/api.test.ts, src/api.ts, src/index.ts, src/parser.ts
Related to #77
Related to https://github.com/0no-co/GraphQLSP/pull/240
Related to https://github.com/urql-graphql/urql/pull/3515
This implements a `graphql.persisted()` function, as per the RFC in #77.
This accepts a `documentId` string and returns a value that matches a GraphQL.js `DocumentNode` shape but contains no definitions. The resulting value contains no reference to the original document, while the return type of `graphql.persisted()` matches the document’s type that's been passed in.
The returned type is also transformed to a more strict type that clearly indicates that the `documentId` is present but that no `definitions` are present.
- Add `graphql.persisted()`
- Add `TadaPersistedDocumentNode`
=> feat: Add `graphql.persisted()` utility to create persisted stand-in documents

.changeset/serious-pears-shave.md, src/__tests__/api.test-d.ts, src/__tests__/fixtures/simpleIntrospection.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/selection.test-d.ts, src/selection.ts
Resolves #100
This improves the type inference for two cases specifically.
When spreading a fragment of an interface (potentially itself) into an interface selection, the type wasn't narrowed even if we had the fragment available and were doing a submatch. This lead to poor type matches when a user wasn't specifying `__typename` above and below the spread although this isn't necessary, since we have all necessary type information.
We can generically solve this by keeping the `PossibleType` narrow, specifically by skipping `getSelection` and using `getPossibleTypeSelectionRec` directly.
Specifically, when using an **unmasked** fragment document and repeating the above a similar issue would occur. In such a case the type checker would be forced to accept two unions of two types that aren't …
=> fix: Fix spreading abstract fragments into abstract selections widening the result type

.changeset/strange-nails-ring.md, src/__tests__/fixtures/simpleIntrospection.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/variables.test-d.ts, src/variables.ts
If I have no `defaultValue`, `getInputObjectTypeRec` will infer my field as `foo?: string | null` when it should be `foo: string`. This is because `getInputObjectTypeRec` only checks for explicity `undefined | null`. Add a test case and fix for this.
* Additional "description" field in test fixture, which has no `defaultValue`
* Bugfix and test
=> fix: Fix input object field introspection with missing `defaultValue` properties

.changeset/long-hornets-develop.md, src/selection.ts, src/variables.ts
Previously, to unwrap `NON_NULL`-like type references, we would have an outer type handling `T | null` for nullable types, and an inner type handling other refrences.
These two steps can be merged by adding an extra argument to the recursive parts of the type reference handler.
This should make some of these types more compact.
- Merge `unwrapType` with `_unwrapTypeRec` into `unwrapTypeRec` in `selection.ts`
- Merge `unwrapType` with `_unwrapTypeRec` into `unwrapTypeRec` in `variables.ts`
- Merge `unwrapTypeRef` with `_unwrapTypeRefRec` into `unwrapTypeRefRec` in `variables.ts`
=> refactor: Merge type unwrapping for types into one step type aliases

.changeset/bright-beds-buy.md, src/api.ts, src/selection.ts, src/utils.ts
- Removed separated `extends infer Result ? Result extends ...` pattern` in favour of duplicating type alias
- Remove `objValues` since it's only used once for more direct pattern (**no discernible perf effect**)
- Simplify `obj` and move usage (**no discernible perf effect**)
=> refactor: Address bad document node inference pattern (perf-cliff)

.changeset/real-goats-run.md, src/__tests__/parser.bench.ts, src/__tests__/parser.test-d.ts, src/__tests__/parser.test.ts, src/__tests__/tokenizer.test-d.ts, src/parser.ts, src/tokenizer.ts
> [!NOTE]  
> This PR is a change to address performance characteristics in a specific part of the type inference process. While it's intended to help with performance, more data and experimentation is needed to further improve `gql.tada`’s performance.
>
> If you have projects or code that can help us reproduce this, or are looking for more information, go to this issue: https://github.com/0no-co/gql.tada/issues/89
Currently, the most expensive phase of parsing a GraphQL document is the phase of turning a string literal into the GraphQL document AST.
We've isolated this to the string literal parsing by basically changing the parser stages commit by commit and observing no discernible performance differences (See: https://github.com/0no-co/gql.tada/commits/refactor/parser-perf-cliffs/) …
=> refactor: Add tokenizer phase to internal document parser

.changeset/four-lies-hide.md, packages/cli-utils/src/index.ts, packages/cli-utils/src/lsp.ts
Add `generate-schema` command which takes a URL | path to a JSON file and outputs a graphql schema. Example:
- `gql-tada generate-schema https://example.com --header 'authorization: bearer token'`
- `gql-tada generate-schema ./introspection.json`
=> feat(cli): add generate schema command

.changeset/eight-yaks-provide.md, src/parser.ts, src/tokenizer.ts
TypeScript also has a tail recursion limit and the changes in #111, while being very effective at reduing parsing overhead times, caused us to now hit the limit of 1,000 when too many ignored tokens were being tokenized.
This PR addresses this by splitting the recursion of ignored tokens back out, reducing the iteration count of tokens for each chain of ignored tokens back to `1`.
That does mean that we still have a limit of 1,000 tokens, including chains of ignored tokens, but from preliminary testing it looks like this is quite reasonable and hard to hit in an app with composed fragments.
I actually like that this may cause us to have a hard limit on which queries are reasonably parsed with `gql.tada`, and when hitting this limit, there's a high chance of a fragment boundary being …
=> fix: Fix tokenizer hitting tail-recursion limit

.changeset/silver-peaches-beam.md, src/__tests__/api.test-d.ts, src/api.ts
Supersedes #121
cc @benjie
This allows `readFragment` to be called on already unmasked fragments, which will most likely happen if we try to call `readFragment` on data that's already typed by (i.e. has already been unwrapped by) another `readFragment` call.
See #121 for more details
- Add overload to `readFragment` that accepts already unwrapped data
=> fix: Allow `readFragment` to be called on already unmasked fragments

.changeset/chilly-cats-smell.md, src/__tests__/api.test-d.ts, src/__tests__/api.test.ts, src/__tests__/namespace.test-d.ts, src/namespace.ts
Resolves #110
This replaces the `$tada.ref` value on the `$tada.fragmentRefs` record for masked fragments with a string literal of the typename of the given fragment, further increasing readability and further decreasing the chance of fragment name conflicts.
Using the symbol as a value flag was redundant, since the entire object is already a value on a symbol property (`$tada.fragmentRefs`) and this change will further increase readability of output types.
It also happens to fix #110, since Remix's `JsonifyObject` does not filter keys but only values.
- Replace `$tada.ref` value with fragment typename
=> fix: Change `fragmentRefs` output to use typename string literal rather than `$tada.ref`

.changeset/wise-flowers-study.md, src/__tests__/api.test-d.ts, src/api.ts, website/src/content/docs/reference/gql-tada-api.mdx
> [!NOTE]  
> It's debatable whether this is a feature or a fix, but since it's a relatively safe addition that complements #98 (for #77) and that we can safely roll back if needed, I'd like to try shipping this as a patch to evaluate this quickly.
This allows the document in `readFragment` to be passed as a generic, removing the need to keep fragments around as a runtime value.
```ts
// previous:
const unmaskedData = readFragment(document, maskedData);
// new:
const unmaskedData = readFragment<typeof document>(maskedData);
```
Replacing `readFragment`'s complex type argument and data generic with an overload is long and wordy, but potentially makes it simpler for TypeScript to evaluate and prevents us having to maintain `mirrorTypeRec`.
In case this is needed, we can add its definition …
=> fix: Allow `readFragment()` to accept fragment document as a generic

.changeset/tender-suits-melt.md, packages/cli-utils/src/index.ts
This PR resolves an issue where `generate-schema` is not correctly handling single headers passed through `options.header`. It would only work correctly if multiple headers were provided. When a single header was passed, it would be ignored and not forwarded to the fetch call.
`@gql.tada/cli-utils` ?
=> fix(cli): generate-schema handle single header

.changeset/fresh-pillows-argue.md, packages/cli-utils/src/index.ts, packages/cli-utils/src/tada.ts, src/cli/index.ts
Resolves #134
Abstract core logic for `generate-schema` and `generate-output` CLI commands into importable Node.js APIs.
The diff is large, but the code is largely the same, mostly just moved around:
- All of the logic in `generateSchema` is unchanged, with the exception of header parsing being pulled out of the function and now headers are passed in as a `Record<string,string>`. Additionally, `cwd` is now an optional parameter (helpful when this methods are called from a directory outside of the directory containing your project's `tsconfig.json` file, e.g., `npm create some-project`).
- `generateTadaTypes` is almost entirely unchanged, `cwd` is now an optional parameter.
=> feat(cli): export cli actions as node apis

.changeset/proud-cats-enjoy.md, src/__tests__/tokenizer.test-d.ts, src/tokenizer.ts
Resolves #139
Instead of handling repeated digits, the tokenizer was only handling a single decimal digit for floats.
- Update tests
- Add missing `skipDigits` cases to `skipFloat`
=> fix: Fix tokenizer not handling floats with repeated decimal digits

.changeset/two-rockets-hear.md, src/__tests__/api.test-d.ts, src/__tests__/api.test.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/selection.test-d.ts, src/__tests__/selection.test.ts, src/__tests__/variables.test-d.ts, src/introspection.ts
Resolves #145 
In the spec it is outlined that `ID` should always serialize to `string` https://spec.graphql.org/October2021/#sec-ID
=> fix: Update default ID scalar type to be `string`

.changeset/rotten-eagles-sort.md, src/__tests__/api.test-d.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/introspection.test-d.ts, src/__tests__/selection.test-d.ts, src/__tests__/selection.test.ts, src/__tests__/variables.test-d.ts, src/api.ts, src/index.ts, src/introspection.ts, src/selection.ts, src/variables.ts
This allows the API to accept a pre-processed “`gql.tada` schema” to be accepted as the `introspection` option (i.e. on `AbstractSetupSchema` / `setupSchema`). Effectively, this means that `mapIntrospection` is used on demand, and only when the input hasn't already been run through `mapIntrospection` before.
This also required us to then split introspection mapping into two steps — one for the general remapping, and one for scalars.
- Split `mapIntrospection` into non-scalar and scalar-adding steps
- Accept pre-processed schema as `introspection` option
=> refactor: Accept pre-processed schemas as introspection inputs

.changeset/real-dogs-swim.md, src/api.ts, src/utils.ts
This was causing an error, depending on the `typescript` version that's installed and used, due to the circular definition of the string literal generics.
=> fix: Remove `stringLiteral` utility type

packages/internal/src/introspection.ts, src/index.ts, src/introspection.ts
TypeScript seems to have hard limits on either:
- how many property types are evaluated
- how many property types on recursive type aliases are evaluated
- how many properties may be printed
None of these limits seem to be cirumventable. Especially the limit on type evaluation is pretty aggressive and replaces the type with the `errorType`, making it hard to figure out how to expand type evaluation and printing after the limit.
Instead, this PR now splits printing up by type to temporarily work around this.
- Split printing of introspection types up to circumvent hard limit
=> fix: Fix preprocessed introspection being cut off by TS

.changeset/kind-geckos-appear.md, packages/cli-utils/src/index.ts
- `$ gql.tada generate-output` now accepts a `--disable-preprocessing` flag
- Preprocessing is enabled by default
=> chore(cli): Enable pre-processing by default

.changeset/warm-timers-join.md, package.json, packages/cli-utils/package.json, packages/internal/package.json, pnpm-lock.yaml
Moves `typescript` to be a peer dependency of all three packages.
This should stop accidental duplicate installations for most cases.
- Add `peerDependencies` per package
- Add pnpm resolution
=> chore: Add peerDependencies on TypeScript

.changeset/smart-yaks-smile.md, src/__tests__/api.test-d.ts, src/__tests__/namespace.test-d.ts, src/__tests__/selection.test-d.ts, src/api.ts, src/namespace.ts, src/utils.ts
This aggressively optimises `getFragmentsOfDocuments` (previously named `getFragmentsOfDocumentsRec`).
In a typical codebase that uses fragment composition properly, there's only so many documents that are in any given hot-path of TypeScript's type checker on evaluation. While we're constrained by wanting to output the resulting `TadaDocumentNode` and its result shape — i.e. not wanting TypeScript to evaluate documents lazily on type hint output — the `getFragmentsOfDocumentsRec` was having a larger impact on performance than expected.
When applied, this PR refactors how fragments are recognised and how we convert the array of fragments, passed to `graphql()`, to a dictionary object.
- Add `FragmentShape` and rename `makeDefinitionDecoration` to `DefinitionDecoration`
- Remove result …
=> refactor: Improve type inference performance of hot-path that computes fragment spreads

.changeset/beige-tools-eat.md, .changeset/swift-dolphins-join.md, packages/cli-utils/src/index.ts, packages/cli-utils/src/lsp.ts, packages/cli-utils/src/tada.ts, packages/internal/package.json, packages/internal/src/index.ts, packages/internal/src/loaders/index.ts, packages/internal/src/loaders/query.ts, packages/internal/src/loaders/sdl.ts, packages/internal/src/loaders/types.ts, packages/internal/src/loaders/url.ts, packages/internal/src/resolve.ts, pnpm-lock.yaml
Resolve #142
Related to #76
This implements reusable loaders for GraphQL schemas from URLs and SDL/JSON files. It unifies the current logic that was used in the CLI and is placed in `@gql.tada/internal` so it's reusable for GraphQLSP.
The new `loadFromURL` loader also checks for schema support and enables the optional introspection features as needed.
- **Remaining TODOs for current code are annotated** (mostly around `tsconfig` handling)
- Implement `loadFromSDL` and `loadFromURL` with watchers
- Replace current CLI logic with loaders
- Clean up `tsconfig` resolving logic
=> feat(internal/cli): Implement schema loaders for URL/SDL inputs

.changeset/twelve-tips-rush.md, packages/cli-utils/src/index.ts, packages/cli-utils/src/lsp.ts, packages/cli-utils/src/tada.ts, packages/internal/src/loaders/index.ts, packages/internal/src/loaders/sdl.ts, packages/internal/src/loaders/types.ts, packages/internal/src/loaders/url.ts
This merges the `SchemaOrigin` type into `@gql.tada/internal` and merges both loaders into one. It also changes the loader interface to automatically reload schemas & introspections on updates and to add a single method to load both the schema and the introspection.
The latter methods are now marked as internal and won't reload the internal data.
- Add `.load()` to loaders`
- Mark old loading methods as internal
- Reload schema/introspection data when watcher notifies
- Add merged `load()` function that accepts `SchemaOrigin`
=> fix(internal): Improve loader by adding a merged loader and incorporating `SchemaOrigin` parsing

.changeset/sweet-bees-unite.md, packages/internal/src/loaders/__tests__/query.test.ts, packages/internal/src/loaders/query.ts
Resolves #171
A regression in introspection due to a typo in the introspection query.
=> fix(internal): Fix loaders not fetching subscriptionType

.changeset/nasty-masks-count.md, packages/cli-utils/package.json, packages/cli-utils/src/commands/doctor.ts, packages/cli-utils/src/doctor.ts, packages/cli-utils/src/index.ts, pnpm-lock.yaml
Addresses part of https://github.com/0no-co/gql.tada/issues/76
This adds `gql.tada doctor` which does the following
- Check whether we have a `package.json`
- Check whether we have a `typescript` dependency > 4.1.0 (when string literal parsing got introduced)
- Check whether `gql.tada` is intalled
- Check whether `@0no-co/graphqlsp` is installed
- Check whether we have a `tsconfig`
- Check whether GraphQLSP is in the tsconfig
- Check whether the `schema` setting is valid
- Check whether the `tadaOutputLocation` is present
=> feat(cli): doctor command

.changeset/silver-cooks-heal.md, packages/cli-utils/LICENSE.md, packages/cli-utils/package.json, packages/cli-utils/src/commands/init.ts, packages/cli-utils/src/index.ts, pnpm-lock.yaml, scripts/rollup.config.mjs
Implements part of #76 
This adds the init command which will ask the user for some information so we can add and install all the tada and LSP features.
=> feat(cli): Init command

.changeset/fair-otters-lie.md, packages/internal/src/introspection/preprocess.ts, src/__tests__/api.test-d.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/introspection.test-d.ts, src/introspection.ts, src/selection.ts, src/variables.ts, website/reference/gql-tada-api.md
Resolves #180
This allows enums to be remapped like scalars. Specifically, if a user has a more qualified type for enums, they should be allowed to completely remap it.
Because `Omit<Schema['types'], keyof Scalars>` is potentially expensive for TypeScript to traverse, this PR avoids this pattern and instead refactors the code that resolves the types for enums. Specifically, `mapEnum` now outputs its type onto the `enumValues` property rather than `type`.
This PR also removes some redundant checks throughout the touched code path.
In practice, the following is now possible:
```ts
enum TestEnum {
value = 'VALUE',
test = 'TEST',
}
const graphql = initGraphQLTada<{
introspection: someIntrospection;
scalars: {
// enum Test { VALUE, TEST }
Test: TestEnum;
};
}>();
```
In the future, we could …
=> feat: Allow enums to be remapped like scalars

.changeset/healthy-shrimps-pretend.md, examples/example-pokemon-api/package.json, examples/example-pokemon-api/po.json, examples/example-pokemon-api/src/components/PokemonList.tsx, packages/cli-utils/package.json, packages/cli-utils/src/commands/check.ts, packages/cli-utils/src/commands/generate-persisted.ts, packages/cli-utils/src/index.ts, packages/cli-utils/src/ts/project.ts, pnpm-lock.yaml
This adds a new command called `generate-persisted` which will go through all the files and generate a JSON file containing all your persisted operations. This can then be used to upload to GraphQL Yoga or some other server to limit the distinct amount of documents that can be sent to the GraphQL server.
Related to https://github.com/0no-co/GraphQLSP/pull/240
Implements part of #76
=> feat(cli): generate persisted operations json files

.changeset/gorgeous-avocados-push.md, examples/example-pokemon-api/src/graphql-cache.d.ts, packages/cli-utils/src/commands/cache.ts, packages/cli-utils/src/index.ts, src/api.ts, src/index.ts
Resolves #160 
This compiles types Ahead Of Time so that we can have a cache and that during dev TypeScript has less to worry about, current output looks like:
```
{
'graphql(`\r\n  fragment PokemonItem on Pokemon {\r\n    id\r\n    name\r\n  }\r\n`)': 'TadaDocumentNode<{ name: string; id: string; }, {}, { fragment: "PokemonItem"; on: "Pokemon"; masked: true; }>',
'graphql(`\r\n  query Pokemons ($limit: Int = 10) {\r\n    pokemons(limit: $limit) {\r\n      id\r\n      ...PokemonItem\r\n    }\r\n  }\r\n`, [PokemonItemFragment])': 'TadaDocumentNode<{ pokemons: ({ [$tada.fragmentRefs]: { PokemonItem: "Pokemon"; }; id: string; } | null)[] | null; 
}, { limit?: number | null | undefined; }, void>'
}
```
=> feat(cli): cache typescript types

.changeset/pretty-falcons-leave.md, packages/internal/package.json, packages/internal/src/introspection/__tests__/preprocess.test.ts, packages/internal/src/introspection/index.ts, packages/internal/src/introspection/minify.ts, packages/internal/src/introspection/output.ts, pnpm-lock.yaml, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/introspection.test-d.ts
Replaces `minifyIntrospectionQuery` to presort some output (`inputFields` and `enumValues` sorting is left alone and left up to the API to sort).
This increases the consistency of our output to the point where we can re-generate `simpleSchema.ts` using our `preprocess` utility then enhance the tests to check against that, as a manual snapshot.
- Replace `minifyIntrospectionQuery` with sorted equivalent
=> chore(internal): Improve consistency of preprocess output

.changeset/plenty-games-smoke.md, packages/internal/src/loaders/__tests__/query.test.ts, packages/internal/src/loaders/query.ts, packages/internal/src/loaders/sdl.ts, packages/internal/src/loaders/url.ts
Resolves #189 
In the October 2021 spec `__Field.args` and `__Directive.args` aren't explicitly said to support `includeDeprecated: Boolean` as an argument.
https://spec.graphql.org/October2021/#sec-The-__Field-Type
https://spec.graphql.org/October2021/#sec-The-__Directive-Type
vs
https://spec.graphql.org/draft/#sec-The-__Field-Type
https://spec.graphql.org/draft/#sec-The-__Directive-Type
=> fix: support opting out of the includeDeprecated argument

packages/cli-utils/src/threads/index.ts
> [!NOTE]
> No changeset, since it's not implementing features yet.
This creates a very small utility that allows us to thread commands without much hassle. It has very limited feature support but the basic idea is that we've got two files.
The command would async-import a separate thread module, which would export an async generator function. This way we can split up the threaded task into multiple signals (unfortunately, no return value though, of course):
```js
// in the main command file
async function mainCommand() {
const { runThing } = await import('./thread');
for await (const signal of runThing(...args)) {
signal;
}
}
```
The threaded file would then expose an async generator function wrapped with the threading utility:
```js
// in the threaded file
async function* _runThing() { …
```
=> feat(cli-utils): Add threading utilities for CLI

.changeset/late-mice-type.md, packages/cli-utils/package.json, packages/cli-utils/src/commands/generate-persisted/thread.ts, pnpm-lock.yaml, src/api.ts
This adds support for `graphql.persisted(hash, document)` so we don't have to advise folks to use APQ when their GraphQL client does not support definition-less documents. To push this out we'll still need to add support to the LSP.
=> feat: Add support for the second argument to `graphql.persisted`

website/.vitepress/config.mts, website/reference/gql-tada-api.md, website/reference/gql-tada-cli.md
This adds `graphql.persisted` to the API documentation and also adds a new page for the CLI.
=> chore(docs): update API documentation with CLI and persisted

.changeset/light-files-travel.md, packages/cli-utils/src/commands/turbo/runner.ts, packages/cli-utils/src/commands/turbo/thread.ts
- Fix crash when `returnType.symbol` is undefined
- Fix output logging all file names when warnings have been discovered in other files
=> fix(cli-utils): Fix `undefined` symbol crash and output bug in `turbo` command

website/.vitepress/config.mts, website/devlog/2024-04-15.md
This is the announcement post for our next major release.
The release itself is represented by this PR: https://github.com/0no-co/gql.tada/pull/174
The announcement will be readable on, once merged: https://gql-tada.0no.co/devlog/2024-04-15
=> docs: Add devlog page on v1.5.0

.changeset/lazy-seas-hunt.md, packages/cli-utils/src/api.ts, packages/cli-utils/src/commands/generate-output/index.ts, packages/cli-utils/src/commands/generate-output/runner.ts, packages/cli-utils/src/commands/generate-persisted/index.ts, packages/cli-utils/src/commands/generate-persisted/runner.ts, packages/cli-utils/src/commands/generate-schema/index.ts, packages/cli-utils/src/commands/generate-schema/runner.ts, packages/cli-utils/src/commands/turbo/index.ts, packages/cli-utils/src/commands/turbo/runner.ts, packages/cli-utils/src/index.ts, packages/cli-utils/src/term/tty.ts
Resolves #134
This exposes all `generate` commands as functions exported by `@gql.tada/cli-utils`, which restores a prior feature as per the linked issue.
=> feat(cli-utils): Expose generate commands as exported functions (Re-add)

.changeset/cool-dolphins-clean.md, packages/cli-utils/src/commands/turbo/thread.ts, src/api.ts
Fixes a regression; the turbo command can accidentally reuse its own cache if we don't disable the cache or remove the cached typings file.
Instead of removing the file or discovering and shadowing it, we now add a global flag to disable the cache entirely while inferring the turbo cache.
- Add `__disableCache` flag to turbo cache
- Add virtual declaration file to declare `__disableCache: true` during `turbo` command
=> fix(cli-utils): Fix `turbo` command reusing its own prior cache output

.changeset/friendly-buses-sniff.md, packages/cli-utils/src/commands/generate-persisted/thread.ts
Resolve #211
Fix incompatible slicing of hash argument with how it's done in GraphQLSP.
This is a regression and I ported this incorrectly.
- Replace `JSON.parse` with `slice` in `generate-persisted`
=> fix(cli-utils): Fix hash parsing in `generate-persisted`

.changeset/tall-starfishes-hunt.md, src/__tests__/api.test-d.ts, src/api.ts, src/namespace.ts
Resolves #215
This prevents `readFragment(data)` from falling back to `any` as a return type when no generic was passed. It also prevents `readFragment(document, data)` to evaluate to `any` when an invalid document is passed. This already errored previously on the `document` argument, but now also prevents `any` from being returned.
- Prevent `readFragment<DocumentType>(data)` from evaluating to `any` when `DocumentType` is left out
- Prevent `readFragment(document, data)` from evaluating to `any`, instead falling back to `unknown` on invalid inputs
=> fix: Prevent `readFragment` from falling back to `any` return types

.changeset/cyan-brooms-hang.md, packages/internal/src/config.ts
=> fix(internal): Fix `parseConfig` not handling `schema.headers`

.changeset/silent-apes-shop.md, packages/cli-utils/src/commands/generate-output/runner.ts
If you use `gql.tada generate --output introspection.ts` and there is no tadaOutputLocation in tsconfig.json, .d.ts contents will be output into a .ts file. Then initGraphQLTada will fail.
=> fix: gql.tada generate --output *.ts was outputting .d.ts

.changeset/friendly-brooms-glow.md, packages/cli-utils/src/commands/generate-output/index.ts, packages/cli-utils/src/commands/generate-output/logger.ts, packages/cli-utils/src/commands/generate-output/runner.ts, packages/cli-utils/src/commands/shared/logger.ts
Follow-up to #225
This adds a hidden `--force-ts-format` option that a hint in the terminal mentions if the output is piped to reactive the `.ts` format for the piped output. Otherwise the `d.ts` output is the default.
This also reorders when the file is generated to prevent future mistakes, like the one in #225. For instance, after that PR the piped output would default to whatever the format of `tadaOutputLocation` is, which is unexpected.
=> fix(cli-utils): Add missing `--force-ts-format` option to `generate-output`

.changeset/selfish-houses-impress.md, packages/cli-utils/src/commands/doctor/helpers/fs.ts, packages/cli-utils/src/commands/doctor/helpers/graphqlConfig.ts, packages/cli-utils/src/commands/doctor/helpers/vscode.ts, packages/cli-utils/src/commands/doctor/helpers/workspaceRoot.ts, packages/cli-utils/src/commands/doctor/logger.ts, packages/cli-utils/src/commands/doctor/runner.ts
Resolves #194
This PR adds an addition to the `doctor` command that attempts to detect VSCode extensions.
When VSCode is installed and the GraphQL Syntax extension for it isn't installed, a warning is issued with a link to the extension.
When the suggested extensions file or the installed extensions contain the VSCode GraphQL Language Service extension and a GraphQL Config is present a warning is issued to prompt the user to check whether `documents` is targeting their files correctly.
This doesn't actually use `graphql-config` to validate the config, since that's quite a huge package for what it does (large dependency to handle TS & ESM files). So, unless we really need that, or want to just load the module from the user `node_modules`, I'd say this should be good enough.
- Add check to …
=> patch(cli-utils): Add VSCode detection and warnings

packages/cli-utils/src/commands/generate-output/index.ts, packages/cli-utils/src/commands/generate-output/runner.ts, packages/cli-utils/src/commands/generate-persisted/index.ts, packages/cli-utils/src/commands/generate-persisted/runner.ts, packages/cli-utils/src/commands/generate-schema/index.ts, packages/cli-utils/src/commands/generate-schema/runner.ts, packages/cli-utils/src/commands/turbo/index.ts, packages/cli-utils/src/commands/turbo/runner.ts, website/.vitepress/theme/style.css, website/get-started/writing-graphql.md, website/graphql/graphql-env.d.ts, website/reference/gql-tada-api.md, website/reference/gql-tada-cli.md, website/reference/graphqlsp-config.md
- Add missing exports of `@gql.tada/cli-utils` to reference docs
- Increase readability of dense code examples
- Increase readability of headings and spacing
- Add TSDocs to `@gql.tada/cli-utils`
- No changeset, since this isn't a relevant change for the library itself, but more for the hints in docs
- Add missing section to "Writing GraphQL" page on `graphql.scalar`
=> docs: Add missing sections and increase readability

.changeset/tame-beers-look.md, .changeset/twenty-students-hunt.md, packages/cli-utils/src/commands/check/runner.ts, packages/cli-utils/src/commands/doctor/runner.ts, packages/cli-utils/src/commands/generate-output/runner.ts, packages/cli-utils/src/commands/generate-persisted/runner.ts, packages/cli-utils/src/commands/generate-schema/runner.ts, packages/cli-utils/src/commands/turbo/runner.ts, packages/internal/src/config.ts, packages/internal/src/loaders/index.ts
See https://github.com/microsoft/TypeScript/pull/58042
This adds support for a `${configDir}` substitution in our configuration.
This, by definition, must always point the path of the evaluated `tsconfig.json`, rather than the `tsconfig.json` the path was sourced from.
Support for this will land in TS with the linked PR.
- Add `rootDir` to `${configPath}` substitution to `getConfig`
=> feat(internal): Add support for `${configDir}` to directory path configs

.changeset/nervous-rice-invent.md, src/__tests__/api.test-d.ts, src/api.ts, src/variables.ts
Related #242
TypeScript is able to trigger error 2353 (“object literals may only specify known properties”) in certain scenarios, when it's obvious to it whether an object literal type has a known set of properties that are accepted.
This fix makes sure that `graphql.scalar()` triggers this check correctly instead of expanding the `value` argument type.
- Keep `value` argument of `graphql.scalar` narrow
- Add tests
=> fix: Ensure TS excess property error can be triggered by `graphql.scalar`

.changeset/nervous-rats-stare.md, .changeset/violet-tools-relax.md, packages/cli-utils/src/ts/container.ts, packages/cli-utils/src/ts/factory.ts, packages/internal/src/config.ts, packages/internal/src/resolve.ts
- Fix resolution of `extends` options
- Fix incorrect `bind` on `getSourceFile`
- Fix resolution of lib files from non-standard paths
=> fix(cli-utils, internal): Fix retrieval of `tsconfig.json` extends and standard TS libs

.changeset/thick-boats-sort.md, bin/cli.js, scripts/eslint-preset.js
We only ever used the CJS entrypoint before and the ESM one was also faulty.
In general, we should try to at least use either of them as needed.
=> fix(cli): Switch between ESM/CJS in CLI entrypoint

.changeset/lemon-moose-applaud.md, packages/cli-utils/package.json, packages/cli-utils/src/ts/transformers/vue.ts, pnpm-lock.yaml
This updates `@vue/language-core` and changes how `VueGeneratedCode` / `VueVirtualCode` is used, since the interface has changed
- Switch between `VueGeneratedCode` and `VueVirtualCode` signatures
- Upgrade `@vue/language-core` but allow `^2.0.0`
=> patch(cli): Upgrade `@vue/language-core` and maintain backwards-compatibility

.changeset/young-lions-work.md, packages/cli-utils/src/ts/factory.ts
In some recent PRs, with `${configDir}` becoming a thing, I got a little confused.
We need `configPath` to resolve to the path of the configuration that contains the GraphQLSP plugin config. However, `projectRoot` always points to the starting folder of the project. However, we now instantiate TypeScript from the `configRoot` rather than `projectRoot`.
=> fix(cli): Change TypeScript instantiation to check from project root

.changeset/nice-pears-pump.md, packages/cli-utils/src/commands/check/runner.ts, packages/cli-utils/src/commands/check/thread.ts, packages/cli-utils/src/commands/doctor/runner.ts, packages/cli-utils/src/commands/generate-output/runner.ts, packages/cli-utils/src/commands/generate-persisted/runner.ts, packages/cli-utils/src/commands/generate-schema/runner.ts, packages/cli-utils/src/commands/turbo/runner.ts, packages/internal/src/config.ts, packages/internal/src/introspection/minify.ts, packages/internal/src/introspection/output.ts, packages/internal/src/introspection/preprocess.ts, packages/internal/src/loaders/index.ts, packages/internal/src/loaders/sdl.ts, packages/internal/src/loaders/types.ts, packages/internal/src/loaders/url.ts, src/__tests__/fixtures/simpleIntrospection.json, src/__tests__/fixtures/simpleIntrospection.ts, src/__tests__/fixtures/simpleSchema.ts, src/api.ts, src/introspection.ts
Related to #248
- Add support for new config format for multiple schemas
- Add utilities to load multiple schemas at the same time
- Pass through `name` from input config to introspection to output format to API
=> feat(internal): Implement initial multi-schema utilities

.changeset/weak-horses-relax.md, packages/internal/src/loaders/index.ts, packages/internal/src/loaders/types.ts
Related to #248
Follow-up to #257
=> patch(internal): Reflect `tada*` options received in `loadRef` to result type

.changeset/honest-suns-hammer.md, packages/cli-utils/src/commands/check/runner.ts, packages/cli-utils/src/commands/check/thread.ts, packages/cli-utils/src/commands/doctor/runner.ts, packages/cli-utils/src/commands/generate-output/runner.ts, packages/cli-utils/src/commands/generate-persisted/logger.ts, packages/cli-utils/src/commands/generate-persisted/runner.ts, packages/cli-utils/src/commands/generate-persisted/thread.ts, packages/cli-utils/src/commands/generate-persisted/types.ts, packages/cli-utils/src/commands/generate-schema/runner.ts, packages/cli-utils/src/commands/shared/logger.ts, packages/cli-utils/src/commands/turbo/logger.ts, packages/cli-utils/src/commands/turbo/runner.ts, packages/cli-utils/src/commands/turbo/thread.ts, packages/cli-utils/src/commands/turbo/types.ts, packages/cli-utils/src/term/tty.ts, packages/cli-utils/src/term/write.ts, packages/internal/src/config.ts
Resolves #248
Related to #257
This implements multi-schema support, as per the RFC, in the CLI. This, together with https://github.com/0no-co/GraphQLSP/pull/303 fully resolves the RFC and implements true multi-schema support.
A given `tsconfig.json` with the plugin configuration can now set up multiple schemas:
```json
{
"compilerOptions": {
"plugins": [
{
"name": "@0no-co/graphqlsp",
"schemas": [
{
"name": "pokemon",
"schema": "./schema.graphql",
"tadaOutputLocation": "./src/graphql-env.d.ts",
"tadaTurboLocation": "./src/graphql-cache.d.ts",
"tadaPersistedLocation": "./src/persisted.json"
},
// ...
]
}
]
}
}
```
These can be used by instantiating them with `initGraphQLTada` via the output file (as specified by `tadaOutputLocation`).
The new configuration is fully validated (as can be …
=> feat(cli-utils): Implement multi-schema support for CLI commands

.changeset/calm-carpets-visit.md, packages/internal/src/config.ts
Resolve #269
Improve error message when:
- `tadaOutputLocation` is missing in `config.schemas[]`
- `tadaOutputLocation`, `tadaPersistedLocation`, or `tadaTurboLocation` aren't unique
=> fix(internal): Improve error messages for schema[] options

.changeset/slimy-boxes-try.md, packages/cli-utils/src/commands/generate-output/runner.ts, packages/cli-utils/src/commands/generate-persisted/index.ts, packages/cli-utils/src/commands/generate-persisted/runner.ts, packages/cli-utils/src/commands/generate-persisted/thread.ts, website/reference/gql-tada-cli.md
This adds missing fragment deduplication to the `generate-persisted` output, and also adds `parse(print())` normalization to the initial document string. The latter can be disabled now using the `--disable-normalization` argument, but it's unlikely that anyone would want to disable this.
> [!NOTE]
> I noticed that `unrollTadaFragments` pre-parses the document. As the function isn't used in `graphqlsp` itself that's likely unnecessary. Removing this allows us to surface parsing errors as warnings to users. That's a separate TODO from this change though.
- Normalize documents output by the `generate persisted` command
- Add `--disable-normalization` argument
- Udpate docs
- Deduplicate fragments in output
=> fix(cli-utils): Add missing deduplication and normalization to `generate persisted` output

.changeset/big-ravens-drum.md, packages/cli-utils/src/commands/doctor/runner.ts, packages/cli-utils/src/commands/init/runner.ts
Relates to #75
This PR adds a new minimum version for TypeScript to support sub-modules in a library for the LSP Plugins. 
- In `doctor` we will check for `gql.tada/ts-plugin` when TS is > 5.5 so folks are pushed to migrate
- In `init` we automatically add `gql.tada/ts-plugin` when TS is > 5.5
=> feat(cli): add `gql.tada/ts-plugin` to init/doctor

.changeset/nice-experts-float.md, packages/cli-utils/package.json, packages/internal/package.json, packages/internal/src/loaders/__tests__/introspection.test.ts, packages/internal/src/loaders/introspection.ts, packages/internal/src/loaders/sdl.ts, packages/internal/src/loaders/url.ts, pnpm-lock.yaml
While we had a strong preference for `graphql@15`, despite a peer dependency, we should open up support to variably accept v15 and — for the future — v17.
This PR adds a `peerDependencies` entry for `graphql` to `@gql.tada/cli-utils`, while also preserving it as a direct dependency. This also widens the `peerDependencies.graphql` entry on `@gql.tada/internal`.
To support the widened range of `graphql` packages, the introspection support queries have been expanded to also run on local `graphql` installations for SDL-loaders.
- Add local support introspection to SDL loader
- Widen peer dependency on `graphql`
=> patch(cli-utils/internal): Add preliminary open support from graphql 15-17

.changeset/cuddly-beers-hug.md, .changeset/thirty-moose-brake.md, packages/internal/src/introspection/minify.ts, packages/internal/src/introspection/preprocess.ts, packages/internal/src/loaders/__tests__/introspection.test.ts, packages/internal/src/loaders/introspection.ts, packages/internal/src/loaders/query.ts, src/__tests__/fixtures/simpleIntrospection.json, src/__tests__/fixtures/simpleIntrospection.ts, src/__tests__/fixtures/simpleSchema.ts, src/__tests__/variables.test-d.ts, src/introspection.ts, src/variables.ts
Adds support for https://github.com/graphql/graphql-spec/pull/825
When we encounter an input marked as `isOneOf: true` we need to create a type that is an _or_ of all the properties spelled out in said input-object.
- In the support-query we check whether `__Type` contains a `isOneOf`
- In the `Introspection` type we add `isOneOf` to the properties
- Add new branch in `variables.ts` that differentiates between `|` and `&`
=> feat(tada): add isOneOf to the introspection type and support query

website/get-started/index.md
Corrects tiny typo on the web docs, incorrectly pluralized word.
Docs/website-only, no functional changes.
=> docs: Tiny typo in web docs

.changeset/new-clouds-argue.md, packages/cli-utils/src/ts/vendor/typescript-vfs.ts
Resolves #289
The missing `system.realpath` method causes other file resolution processes to fail. Namely, this causes module resolution to act incorrectly with `pnpm`-installed dependencies and hence fails quite quickly since `gql.tada` depends on `@0no-co/graphql.web`
- Add missing `realpath` method to `createFSBackedSystem`
=> fix(cli-utils): Fix modules not being resolved correctly with pnpm-installed `gql.tada`

.changeset/silver-eels-rhyme.md, packages/cli-utils/src/ts/transformers/vue.ts
It looks like another breaking change apart from the rename to `getBasePlugins` is that we stopped using `vue-sfc` by default which means that we lose out on variables declared in the global scope. This addresses that by pushing this to the plugins array again.
Currently seeing whether it would be safer to use `createVueLanguagePlugin` instead
=> fix(cli-utils): vue losing the graphql call due to missing sfc plugin

.changeset/nervous-pumpkins-prove.md, packages/internal/src/loaders/introspection.ts, packages/internal/src/loaders/url.ts
Resolves #316
This allows GraphQL support to be determined from an introspection result. This is a suboptimal path as we potentially do two introspections on a first introspection request. However, this isn't much different from what we did before, which included running assuming full support then falling back to no support of features.
- Add deriving support from full introspection result to URL loader
=> fix(internal): Allow determine GraphQL support from introspection result

.changeset/hungry-needles-rule.md, src/__tests__/selection.test-d.ts, src/selection.ts
Patterns that require a `T | {}` optionality being merged into selections are causing exponential complexity. This is because all fields in a selection are merged using the `obj` utility. However, `T | {}` causes `2^n` complexity in evaluating and flattening types in TypeScript.
This is because for each `A & (B | {})` merge two variants are created, `(A & B) | (A & {})`. For each subsequent addition (e.g. `A & (B | {}) & (C | {})`) the complexity doubles (`(A & B) | (A & C) | (A & B & C) | A`. This can quickly cause a recursion complexity error in TypeScript once we reach the limit of 16 variants.
This fix addresses this by limiting the flattening of fields to just the fields and not optional sub-selections.
This fix however does have a few problems:
- We can probably add a shortcut for …
=> fix(gql.tada): Fix recursive optional fragment types causing exponential complexity

.changeset/gentle-elephants-breathe.md, packages/cli-utils/src/term/write.ts
Resolves #326
A prior regression meant that `process.exitCode` wasn't being set any longer.
This has now been fixed and errors now cause `process.exitCode` to be set correctly and as intended again.
- Add missing `CLIError#exit` to `process.exitCode` copying
=> fix(cli-utils): Fix regressed CLI exit codes on errors

.changeset/big-ravens-drum.md, .changeset/spotty-crabs-report.md, .gitignore, examples/example-pokemon-api/package.json, examples/example-pokemon-svelte/package.json, examples/example-pokemon-vue/package.json, package.json, packages/cli-utils/package.json, packages/cli-utils/src/commands/doctor/runner.ts, packages/cli-utils/src/commands/init/runner.ts, packages/cli-utils/src/utils/semver.ts, packages/internal/package.json, packages/internal/src/resolve.ts, pnpm-lock.yaml, src/ts-plugin/index.ts
Dependent on https://github.com/microsoft/TypeScript/pull/57266
Resolves #75
We're waiting for TypeScript to support sub-paths for tsserver plugins to ease the installation instructions back down to a single package and avoid having to explain the different between `@0no-co/graphqlsp` and `gql.tada` to people.
This would turn `gql.tada` into a standalone entrypoint package for its experience.
- Add `gql.tada/ts-plugin` alias
=> feat: Add `gql.tada/ts-plugin` alias

website/.vitepress/theme/style.css, website/get-started/index.md, website/get-started/installation.md, website/get-started/workflows.md, website/guides/fragment-colocation.md, website/guides/multiple-schemas.md, website/guides/persisted-documents.md, website/reference/config-format.md, website/reference/gql-tada-api.md, website/reference/gql-tada-cli.md
- Change references to `@0no-co/graphqlsp` to `gql.tada/ts-plugin`
- Add sections for alternative setup instructions to Installation page
- Separate section for VSCode
- New section for `@0no-co/graphqlsp` in TypeScript <5.5
- Simplify all references to GraphQLSP by referring to it as the "TypeScript plugin"
- Rephrase a couple of outdated terms ("`introspection` file" to "typings output file")
- Rephrase several sections to make it easier to understand the TypeScript plugin / type system relationship
This will still need some updates to the `Introduction` page.
Currenty, I'm thinking that we may want to split the "How it works" section out, and remove the support section (maybe supplementing the latter with some additions to "Writing GraphQL")
The introduction page could generally maybe …
=> docs: Update for 1.8.0 changes (TypeScript 5.5)

.changeset/happy-cheetahs-provide.md, .changeset/thin-cats-tell.md, packages/cli-utils/src/commands/check/thread.ts, packages/internal/src/config.ts
Resolves https://github.com/0no-co/gql.tada/issues/323
The field-usage heuristics see the generated functions as two different scopes so the field-usage and co-located fragment tracking fails to report correctly, hence for now we disable this when analyzing svelte/vue.
=> chore(cli): disable field-usage and colocated fragments for vue/svelte 

website/get-started/installation.md, website/get-started/workflows.md
When starting with gql.data, I spent quite some time trying to understand how to retrieve the schema without leaking API tokens in `tsconfig.json`.
This is the solution I'm using in my projects. It proves to be quite effective and even simple, despite the convoluted usage of single and double quotes required to control when shell interpolates the variable.
It uses the `dotenv` command, which is pretty common to have in dev dependencies.
=> docs: Add header hint for `generate-schema` to "Workflows" page

.changeset/shy-experts-pump.md, examples/example-pokemon-api/src/graphql-env.d.ts, examples/example-pokemon-svelte/src/graphql-env.d.ts, examples/example-pokemon-vue/src/graphql-env.d.ts, packages/internal/src/introspection/output.ts, packages/internal/src/introspection/preprocess.ts
Resolves #348
Not exporting types separately in composite projects seems to cause a serialization diagnostic error. This seems to be a bug in TypeScript but worked around quite easily.
- Output separate `introspection_types` export for pre-processed `.d.ts` typings output file unless preprocessing is disabled
=> fix(internal): Export types in output typings file separately for composite projects

.changeset/quiet-panthers-wink.md, src/__tests__/api.test-d.ts, src/api.ts
Previously, when a fragment as annotated to be optional with a directive (such as `@skip`, `@include`, or `@defer`), `readFragment` wasn't able to match such a type. Optional fragments are typed as `T | {}` since they may be optional, however, no match pattern in `readFragment` was able to match this pattern.
The patterns have now been extended to match these cases and pass them through as `T | {}` on the return type.
- Refactor inferred `readFragment` pattern to add `T` type to match all patterns in fewer overloads
- Extend explicit-generic-overloads to account for `| {}` explicitly (doubling them)
=> patch: Match optional (`T | {}`) fragment data

.changeset/shaggy-rivers-move.md, packages/cli-utils/package.json, packages/cli-utils/src/ts/transformers/index.ts, packages/cli-utils/src/ts/transformers/vue.ts, pnpm-lock.yaml
Similar past change: https://github.com/0no-co/gql.tada/pull/305
This supports changes in `@vue/language-core` which renamed `getBasePlugins` (again) to `createPlugins`, which caused Vue files to again not be parsed.
To prevent further delays in debugging such errors, there's now a `check` function that outputs an explicit error if `VueVirtualCode` or `createPlugins` are undefined, which is a pretty sure signal of breaking changes.
- Upgrade internal test version of `@vue/language-core`
- Fix `@vue/language-core` version, which was accidentally bumped (set to `~2.0.0`)
- Add `check` function with special error for breaking Vue changes
=> fix(cli-utils): Support `@vue/language-core@2.0.28` changes

.changeset/ten-owls-vanish.md, packages/cli-utils/src/ts/factory.ts
Increase stack trace limit to `25` when TypeScript is used, as the default of `10` isn't enough to properly debug issues in most (if not all) cases that TypeScript's type checker or program is involved in a crash.
- Add `bumpStackTraceLimit` utility
=> patch(cli-utils): Bump stack trace limit when TypeScript is used

.changeset/gold-balloons-count.md, packages/cli-utils/src/ts/factory.ts
Related: https://github.com/0no-co/gql.tada/issues/347#issuecomment-2258746859
Using `NodeNext`/`Node16` is almost always a mistake. This will disallow extension-less imports, and is almost always not preferred over `Bundler`. In practice, `NodeNext` is only the `Bundler` resolution with the added restriction, and if it's used and we get module resolution errors, this was likely a mistake. Overriding it is always safe since it's a super-set of `NodeNext`.
- Override `moduleResolution` to `Bundler` if it's `NodeNext`/`Node16`
=> fix(cli-utils): Add `moduleResolution` override for `NodeNext`/`Node16`

.changeset/curvy-mirrors-warn.md, packages/cli-utils/src/commands/doctor/helpers/versions.ts, packages/cli-utils/src/commands/doctor/runner.ts
See: #357
While it's correct that we'd want users to install `gql.tada` locally in packages, depending on where the command is run, the local `package.json` may not contain all dependencies. This lifts this limitation and basically makes sure of the basics:
- `typescript` should be available via a direct `import()` since it's a direct dependency of the CLI (via peer)
- `@0no-co/graphqlsp` should be available via a direct `require()` from the package since it's a direct dependency of the CLI (via peer)
- `gql.tada` should be available via a `require()` from the working directory, since it must be present to start up the CLI
This should generally allow us to be a little more lenient in the `doctor` checks.
- Add `helpers/versions` to doctor for version checking
=> patch(cli-utils): Add fallbacks for version checks to `doctor` command

.changeset/late-cougars-act.md, packages/cli-utils/src/threads/index.ts
The default serializer/transferables logic doesn't transfer extra properties on Errors. It can correctly transfers stacktraces and the message of the original error, but doesn't transfers extras such as the `name` property.
When applied, this change adds an extra serialization step for errors that transfers extra properties over.
Without this logic, it wouldn't be possible for us to add special handling to errors by their type/name.
- Add `extra` properties for errors to transfer on throws in thread
=> fix(cli-utils): When threading, transfer extra error properties to host

.changeset/three-jobs-boil.md, src/__tests__/api.test-d.ts, src/selection.ts
Follow-up to #102
Resolves #365
The differentiation when going from a narrow to a wide type can still cause confusion when the `__typename` field isn't included on the concrete/base type i.e. on the fragment that includes the abstract interface type.
This PR adds another optional `__typename` field to add disambiguation and avoid any confusion caused by this.
- Disambiguate fragment spreads automatically using `__typename?: PossibleType` field
=> fix: Protect against missing typename fields on base types

.changeset/wild-tables-serve.md, src/selection.ts
I noticed that the types on interfaces and unions could become quite complex and the type output wasn't nice to read.
Instead of asking TypeScript to narrow using an intersection, we can instead manually narrow any union, since they're expanded in `extends` types.
**Note:** I'm not 100% sure what the type performance impact of this change might be, but the benchmarks indicate that it's negligible.
Follow-up to #368
But issue is also visible before the above PR was merged. It was just rarer
- Expand union types before intersecting
=> fix: Improve type output for narrowed interfaces (intersect members of unions instead)

.changeset/hip-sheep-provide.md, src/api.ts
All `readFragment<Document>(data)` calls receive explicit generics. However, they contained a `= never` default, which was entirely redundant.
**Side-note:** Any `readFragment<Document>({})` are always valid. Unknown data is now accepted. This is unfortunate, but not fixeable without a second generic, which isn't possible in TS.
- Remove `= never` from `readFragment` overloads with explicit `Document` generics
=> fix: Remove redundant `never` default from `readFragment` with explicit generic

.changeset/ten-taxis-shop.md, src/__tests__/api.test-d.ts, src/api.ts
When an input with a `__typename` property is passed to `readFragment`, we can narrow the output type by this input property
- Add `resultOfT` helper that, similarly to `narrowTypename` in `selection.ts` narrows the output type of `readFragment`
=> fix: Add type narrowing to `readFragment`

.changeset/empty-hairs-punch.md, src/api.ts
Resolves #376
We can make it more obvious how to explicitly declare a type for the `initGraphQLTada<>()` return type. Currently, replicating it seems unintuitive due to the unexported type helpers that `GraphQLTadaAPI` requires.
Hence, we can create an overloading type alias called `initGraphQLTada<>` that evaluates to this type and is then reused by `graphql` and `initGraphQLTada<>()`'s return type to explicitly make the type clear.
- Add `initGraphQLTada<>` type alias
=> fix: Add missing type alias for `initGraphQLTada`

.changeset/fluffy-seahorses-flow.md, packages/internal/src/resolve.ts
Given the following `tsconfig.json` setup:
```
// tsconfig.json
{
"extends": ["./tsconfig.app.json", "./tsconfig.gql-tada.json"]
}
// tsconfig.app.json
{
"compilerOptions": {
// some options here
}
}
// tsconfig.gql-tada.json
{
"compilerOptions": {
"plugins": [
{
"name": "gql.tada/ts-plugin",
// schema config
}
]
}
}
```
I encounter the following error:
`Could not find a valid GraphQLSP plugin entry in: tsconfig.json`
The code in this PR fixes the issue for me, but there aren't unit tests specifically for this area of code so not sure of any adverse effects.
The change was pretty straightforward in just modifying `return load(tsconfigPath)` to be `return await load(tsconfigPath)` so that exceptions thrown when trying to load nested tsconfig "extends" elements are caught (and swallowed) by …
=> fix: handle multiple tsconfig `extends` for resolving GraphQLSP plugin entry

.changeset/friendly-dolls-lick.md, packages/cli-utils/src/commands/generate-persisted/thread.ts
Resolves #387 
This guarantees correctness as the API won't know about this directive, this will also need to happen on the LSP side of things.
=> fix(cli-utils): Strip unmask directive during persisted-ops generation

.changeset/honest-donkeys-pay.md, src/__tests__/utils.test.ts, src/api.ts, src/utils.ts
Unfortunately `graphql-tag` has several quirks, including concatenating all interpolations' source bodies and parsing them all as a whole. While it does so, it blindly uses `document.loc` without checking whether this property is `undefined`, despite it being optional.
This leads to an incompatibility since it's purposefully left out in `graphql.web`. However, during a gradual migration it's conceivable that `gql.tada`'s `graphql()` fragments will be interpolated into `graphql-tag`'s tag functions.
While this isn't recommended, since it's also possible to "blanket-migrate" from `graphql-tag`'s `gql` function to `graphql()` functions from `gql.tada`, this would likely require codemods, so a partial migration isn't unlikely.
To solve this, we now add a `loc` getter, which creates a …
=> fix: Add `loc` getter on fragment documents for `graphql-tag` inter-compatibility

.changeset/forty-paws-yawn.md, src/api.ts
Resolves #398
- Add missing setter (`set loc`) to document nodes output by `graphql`
=> fix: Add missing setter to `loc` property

.changeset/rotten-balloons-bow.md, packages/cli-utils/src/commands/shared/utils.ts
Related to https://github.com/0no-co/GraphQLSP/issues/357
Creates directories recursively if the CLI is trying to write to a directory that doesn't exist yet.
The symbolic link check is a bit scuffed, but basically just protects us against creating a directory at the leaf path, if a conflicting symlink exists and points to a directory, since this will most certainly cause an issue. Otherwise, at non-leaf paths the directory would be resolved normally anyway.
- Add recursive `mkdir` if target doesn't exist
=> fix(cli-utils): Create directories in CLI when writing to non-existent paths

website/get-started/installation.md, website/get-started/workflows.md, website/guides/multiple-schemas.md, website/guides/persisted-documents.md, website/reference/config-format.md, website/reference/gql-tada-api.md, website/reference/gql-tada-cli.md
See #404 and similar reports
On Windows, it's generally harder to execute commands such as `gql.tada` containing dots. Instead, we should consistently refer people to our `gql-tada` alias for the command. This PR also changes a couple of references from "the `gql.tada` CLI/commands" to "the `gql-tada` CLI/commands"
- Replace all `gql.tada` CLI and command references with `gql-tada`
=> docs: Update `gql.tada` CLI/commands to refer to `gql-tada` instead

.changeset/mighty-dots-applaud.md, packages/cli-utils/src/commands/turbo/thread.ts, packages/cli-utils/src/ts/factory.ts
Resolves #406
Due to a misuse of our own `addSourceFile` method's second argument, we regressed and the `turbo` command wasn't disabling the cached turbo file anymore.
This meant that any subsequent run of the `turbo` command would use the last run's type cache, which wasn't intentional.
To combat this the argument has been removed entirely, as we don't use it ourselves.
- Remove `addRootNames` argument and instead always register a root name for `addSourceFile` calls
=> fix(cli-utils): Fix regression causing `turbo` command to reuse the `turbo` cache itself

website/get-started/installation.md
Fix incorrect anchor link in documentation that points to the VSCode setup section. The current link uses `#vscode-settings-and-plugins` while the correct anchor should be `#vscode-setup`.
On the installation guide [here](https://gql-tada.0no.co/get-started/installation#prior-to-typescript-5-5) :
The Read about link doesn't redirect you to any section.
- Updates anchor link in the VSCode setup notice box to correctly point to the intended section
- Noteworthy file : `website/get-started/installation.md`
- No breaking changes
```html
<a href="#vscode-settings-and-plugins">Read about these steps in the "VSCode Setup" section below.</a>
```
```html
<a href="#vscode-setup">Read about these steps in the "VSCode Setup" section below.</a>
```
=> docs: Fix anchor link to VSCode setup section

.changeset/calm-donuts-juggle.md, src/__tests__/tokenizer.test-d.ts, src/tokenizer.ts
Resolves #448
We didn't handle trailing comments correctly. This specifically occurs when the trailing comment does not end in a newline character, which we enforced before, which caused no pattern in the tokenizer to match.
Instead, we now match comments until the end of the string as well.
This wasn't noticed before due to auto-formatting by prettier being quite common, and formatting in general being mostly expected.
Benchmarks are neutral when applying these changes.
- Move comment handling to `skipIgnored`
- Add case to match comment matches until end of input
=> fix: Handle trailing comments without newline characters

.changeset/cyan-camels-listen.md, packages/cli-utils/src/commands/turbo/thread.ts
Resolves https://github.com/0no-co/gql.tada/issues/445
This adds support for externally defined scalars, the addition of this flag means that we just copy over references and it's kind of a "trust me" on whether the import is present. This makes the output less clean as it will be littered with `import().type`, however this isn't a file that is meant to be read so...
The alternative solution would have been to analyze the setup file and copy over the imports into the generated cache file. This could have been tricky as the cache file is allowed to be on any level compared to the setup file and even an external package so I opted for this approach instead.
=> Fix external scalars in turbo

.changeset/modern-walls-relax.md, packages/cli-utils/src/commands/doctor/helpers/__tests__/versions.test.ts, packages/cli-utils/src/commands/doctor/helpers/versions.ts
Resolves https://github.com/0no-co/gql.tada/issues/446
This adds support for `pnpm workspace catalog`, this basically entails that a version can be specified as `catalog:` which forces us to look it up in the `pnpm-workspace.yaml` file.
I am working on tests but I forgot how tedious it is to make these things work on Windows devices 😅 Yikes to the test timeout in CI, this is due to the async import of typescript just taking long.
=> Add support for vitest workspace catalogs

.changeset/gentle-carpets-sing.md, examples/example-pokemon-api/src/Test.ts, examples/example-pokemon-api/src/components/graphql-cache.d.ts, examples/example-pokemon-api/src/graphql-cache.d.ts, examples/example-pokemon-api/src/graphql.ts, examples/example-pokemon-api/tsconfig.json, packages/cli-utils/src/commands/turbo/runner.ts, packages/cli-utils/src/commands/turbo/thread.ts, packages/cli-utils/src/commands/turbo/types.ts, packages/cli-utils/src/ts/factory.ts
When generating the turbo cache, we collect all the `graphql()` call expressions and their types, but we weren't copying over the imports from the GraphQL source files (like `examples/example-pokemon-api/src/graphql.ts`). This meant the generated cache file was missing imports like:
```ts
import type { introspection } from './graphql-env.d.ts';
import type { Test } from './Test';
```
- **Trace graphql() calls back to source**: Added AST traversal to find where each `graphql()` call is imported from
- **Collect imports**: Extract all import statements from GraphQL source files 
- **Adjust paths**: Update relative import paths to work from the turbo cache location
- **Avoid circular imports**: Filter out any imports that would reference the output files themselves
- **Deduplicate**: Only …
=> Fix external scalars 2

.changeset/gentle-carpets-sing.md, examples/example-pokemon-api/src/Test.ts, examples/example-pokemon-api/src/components/graphql-cache.d.ts, examples/example-pokemon-api/src/graphql-cache.d.ts, examples/example-pokemon-api/src/graphql.ts, examples/example-pokemon-api/tsconfig.json, packages/cli-utils/src/commands/turbo/runner.ts, packages/cli-utils/src/commands/turbo/thread.ts, packages/cli-utils/src/commands/turbo/types.ts, packages/cli-utils/src/ts/factory.ts
Reverts https://github.com/0no-co/gql.tada/pull/461
Closes #470 
Fixes https://github.com/0no-co/gql.tada/issues/445
We'll probably need a slightly different approach where we derive the file `graphql` is being imported from or leverage the global `tadaOutputLocation`. When we have this file we want to collect all imports in AST traversal and prepend it to the turbo file.
=> Fix external scalars

.changeset/clean-mails-exist.md, src/__tests__/parser.test-d.ts, src/parser.ts
Similar to https://github.com/0no-co/graphql.web/pull/59 but in the TS parser, making sure this doesn't start failing. For the LSP to support this we'll need to upgrade GraphQL.web
=> Support parsing executable definition descriptions

.changeset/violet-dogs-thank.md, packages/cli-utils/src/commands/turbo/thread.ts, packages/cli-utils/src/ts/factory.ts
Resolves #480 
~~We should not merge this right away as we need to investigate the why of this original default and whether it's still needed~~
We should revisit the Bundler fallback in the next major, for the time being I've found a backwards compat way.
=> Add support for nodenext
